version: '2'

services:
  db:
    image: registry.centos.org/postgresql/postgresql:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword
    networks:
      - default
  core:
    image: fabric8-services/fabric8-wit:latest
    command: -config /usr/local/wit/etc/config.yaml
    environment:
      F8_POSTGRES_HOST: db
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - db
