-- When created, a work item link type didn't know about any space and thus its
-- name was only allowed to be used once per link category. Now, with spaces,
-- the same unique index shall span the name, the category and the space.
